### PR TITLE
Fix #274, Add quotes to env var value in docker.env file

### LINKED ISSUE #274: Environment variables should be added to docker.env between quotes
Otherwise doing `source docker.env` will fail if there's variables with spaces.
Which happens with RESIN_HOST_OS_VERSION on resin.io devices.

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

File: debian/entry.sh [hunk 1]
```diff
@@ -58,7 +58,7 @@ function init_systemd()
 {
 	GREEN='\033[0;32m'
 	echo -e "${GREEN}Systemd init system enabled."
-	env > /etc/docker.env
+	env | sed 's/"/\\"/g' | sed 's/^\([a-zA-Z0-9_]*\)=\(.*\)$/\1="\2"/g' > /etc/docker.env
```
Comment (petrosagg) [inline debian/entry.sh]: Can we use shell escaping instead? I haven't tested if it works but if it does it will take care of all the edge cases.
```bash
for var in $(compgen -e); do
    printf '%q=%q\n' "$var" "${!var}"
done > /etc/docker.env
```

Comment (nghiant2710) [inline debian/entry.sh]: Updated!

File: debian/amd64/jessie/entry.sh [hunk 2]
```diff
@@ -58,7 +58,9 @@ function init_systemd()
 {
 	GREEN='\033[0;32m'
 	echo -e "${GREEN}Systemd init system enabled."
-	env > /etc/docker.env
+	for var in $(compgen -e); do
+    	printf '%q="%q"\n' "$var" "${!var}"
```
Comment (petrosagg) [inline debian/amd64/jessie/entry.sh]: all oft these should be indented one tab level in. consider it approved once this is fixed
