### PR TITLE
fix #50. Fix imprope CMD instruction parsing

### LINKED ISSUE #50: Improper CMD instruction parsing when using the CMD shell form
This investigation started when we noticed that [this](https://github.com/resin-io-projects/electron-rpi-quick-start) project wouldn't run as expected when installed on an Rpi2. Instead of the electron app, the application only presented a single xterminal, which is the default behavior of xinit.

Let's start by looking into the base image hierarchy. There we find the [armv7hf-debian](https://github.com/resin-io-library/base-images/blob/master/systemd/armv7hf/jessie/Dockerfile) base image. In its Dockerfile we can find this instruction:

```
ENTRYPOINT ["/usr/bin/entry.sh"]
```

Now our affected application uses a Dockerfile.template, which is parsed and results in a Dockerfile that looks like this:

```
FROM resin/raspberrypi2-node:4.0.0
[...]
CMD xinit /usr/src/app/launch_app.sh --kiosk -- -nocursor
```

The effect of the CMD command is that it passes arguments to the ENTRYPOINT command; for more information you can refer to the related *[Exec form ENTRYPOINT example](http://docs.docker.com/engine/reference/builder/#entrypoint)* in the official Docker documentation.

Also notice that in our app's Dockerfile we use the CMD shell form, so the command will execute in ```/bin/sh -c```. As a result, the command that will be executed is:

```
/usr/bin/entry.sh /usr/sh -c xinit /usr/src/app/launch_app.sh --kiosk -- -nocursor
```

The arguments are then parsed by the **entry.sh** file:

```bash
if [ "$INITSYSTEM" = "on" ]; then
[...]
  echo -e "#!/bin/bash\n exec $@" > /etc/resinApp.sh
  chmod +x /etc/resinApp.sh
[...]
```

So the final resinApp.sh on the device looks like this:

```bash
#!/bin/bash
exec /usr/sh -c xinit /usr/src/app/launch_app.sh --kiosk -- -nocursor
```

And there's the issue. ```/bin/sh -c``` expects a string wrapped in '' or "", or else it needs special care to pass the arguments after the next parameter. In our case, xinit will be executed and the rest of the parameters will simply be ignored, as we can see in the related [sh(1)](https://www.freebsd.org/cgi/man.cgi?query=sh&sektion=&n=1) section:

```
The -c option causes the commands to be read from the string operand
     instead of	from the standard input.  Keep in mind that this option	only
     accepts a single string as	its argument, hence multi-word strings must be
     quoted.
```

Now I'm not sure if this is a docker issue or ours, some possible solutions are:

1. Support only the CMD exec form (```CMD ["command, "param1", "param2"]```) and update the docs accordingly.
2. Update the scripts to handle CMD shell form, i.e wrap the command properly in "".

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

**Comment by nghiant2710** [comment]
Moving https://github.com/resin-io-library/base-images/pull/51 here

**Comment by petrosagg** [comment]
Hey, can you rebase this branch on top of origin/master instead of having a merge commit in the PR?

**Comment by nghiant2710** [comment]
@petrosagg, can you review this PR then I will tidy up afterward

File: systemd/amd64/jessie/entry.sh [hunk 1]
```diff
@@ -28,7 +46,9 @@ if [ "$INITSYSTEM" = "on" ]; then
 	echo -e "${GREEN}Systemd init system enabled."
 	env > /etc/docker.env
 
-	echo -e "#!/bin/bash\n exec $@" > /etc/resinApp.sh
```
Comment (petrosagg) [inline systemd/amd64/jessie/entry.sh]: Why don't we just replace this with

```bash
printf '#!/bin/bash\n exec ' > /etc/resinApp.sh
printf '%q ' "$0" "$@" > /etc/resinApp.sh
```

instead of doing all the above?

Comment (nghiant2710) [inline systemd/amd64/jessie/entry.sh]: @petrosagg, Updated!

Switching to this way because it behaves exactly as how docker handles CMD command. After doing some tests, the old solution behavior is not the same as docker when we use CMD in exec form to call a shell (ex `CMD [ "sh", "-c", "echo 123 345 456\'$%^£$%^" ]`)

**Comment by petrosagg** [comment]
SGTM
