### PR TITLE
Fix #250, add `fg`command to fix the broken interactive shell when runs container locally.

### LINKED ISSUE #228: INITSYSTEM should also accept 1 or 0 as well as on and off
relates to https://github.com/resin-io/hq/issues/364

### LINKED ISSUE #250: Unable to launch interactive shell when running the container locally
With the current implementation https://github.com/resin-io-library/base-images/blob/master/debian/entry.sh#L84-L86, we will never be able to start an interactive shell when running the container locally, the reason is CMD will be started in background so command like `docker run -it resin/raspberrypi3-debian:jessie /bin/bash` won't work as expected. This is really bad since our base images are widely used by Docker community.

Adding `fg` command after having run `wait $pid` is the solution here but there is another issue since ` `fg` always returns exit code 1 if there is no background process to attach to so we need a way to pass the correct exit code in that case.

There were few PRs to fix this issue:
https://github.com/resin-io-library/base-images/pull/186 (https://github.com/resin-io-library/base-images/commit/b18bd44badeccae9cf7b549c96b6fcb2f861bfdc)
https://github.com/resin-io-library/base-images/pull/191 (https://github.com/resin-io-library/base-images/commit/b789b41f43b5d92d069e2ec0878f0b130c90947a)
https://github.com/resin-io-library/base-images/pull/227 (https://github.com/resin-io-library/base-images/commit/4be4d71862db662c603aa090ed2d8f9ac69d5c96)
but none of them completely solves this.

This PR https://github.com/resin-io-library/base-images/pull/238 will address all the problems that relate to this issue.

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

File: alpine/entry.sh [hunk 1]
```diff
@@ -1,11 +1,16 @@
...
 
+# On ResinOS 2.x devices, the hostname is set by the hostOS.
+# For backward compatibility, we only update the hostname for ResinOS 1.x devices.
 function update_hostname()
 {
-	HOSTNAME="$HOSTNAME-${RESIN_DEVICE_UUID:0:7}"
-	echo $HOSTNAME > /etc/hostname
-	echo "127.0.1.1 $HOSTNAME" >> /etc/hosts
-	hostname "$HOSTNAME"
+	if [ ${RESIN_DEVICE_UUID:0:7} != $(hostname -s | cut -c 1-7) ]; then
```
Comment (Page-) [inline alpine/entry.sh]: Can this be:
```bash
if [ ${RESIN_DEVICE_UUID:0:7} != ${HOSTNAME:0:7} ]; then
```
in order to make it a bit easier to see that the same slice is being compared

File: alpine/entry.sh [hunk 2]
```diff
@@ -61,6 +61,23 @@ function init_non_openrc()
 	fi
 }
 
+INITSYSTEM=$(echo "$INITSYSTEM" | awk '{print tolower($0)}')
+
+case "$INITSYSTEM" in
+	'1')
```
Comment (Page-) [inline alpine/entry.sh]: Is this able to be
```bash
	'1' | 'true')
		INITSYSTEM='on'
```
?

Comment (nghiant2710) [inline alpine/entry.sh]: Updated!

File: alpine/entry.sh (hunk 1 above)
Comment (nghiant2710) [inline alpine/entry.sh]: Updated!

File: debian/entry.sh [hunk 3]
```diff
@@ -90,6 +90,8 @@ function init_non_systemd()
 		"$CMD" "$@" &
 		pid=$!
 		wait "$pid"
+		exit_code=$?
+		fg > /dev/null || exit "$exit_code"
```
Comment (petrosagg) [inline debian/entry.sh]: `fg` was not deleted in the commit referenced in your commit message. Can you open an issue in this repo that clearly states the problem you're trying to fix here, including a minimal testcase? I don't understand what's going on with the exit codes and what we're trying to fix

Comment (nghiant2710) [inline debian/entry.sh]: @petrosagg https://github.com/resin-io-library/base-images/issues/250

Comment (petrosagg) [inline debian/entry.sh]: this PR doesn't have a "fixes #250" anywhere. Also, the issue doesn't explain why the issue happens, it just states that "interactive shell doesn't work". Can you explain the reason and what is going on with the script, the job, background, foreground etc?

Comment (nghiant2710) [inline debian/entry.sh]: @petrosagg I've update the commit message and https://github.com/resin-io-library/base-images/issues/250 to explain more about this issue.

Comment (petrosagg) [inline debian/entry.sh]: How does this fix the case where a user does `docker run -it ... /bin/bash`? From what I understand `/bin/bash` will be run in the background and then we'll block at `wait "$pid"`. And only after this happens will `fg` run.

Comment (nghiant2710) [inline debian/entry.sh]: @petrosagg, when '/bin/bash' is started in the background that means it will immediately receive a SIGTSTP on start which puts the process on hold. Then `wait` command will catch this state change and pass on to `fg` which brings the shell back to foreground.
